export default [
  {
    title: "Software Engineer @ Evalink",
    currentJob: true,
    startDate: "April 2024",
    endDate: "Present",
    description: [
      "Maintains web-based automation systems for payment processing using Robotic Process Automation (RPA)",
      "Maintains most interfaces that integrate with the automated systems, ensuring platform stability and adaptability to changes in applications",
      "Focus on optimizing the user experience while collaborating with back-end systems to ensure efficient performance",
    ],
    techStack: [
      "NextJS",
      "React",
      "ChakraUI",
      "TanStack Query",
      "Axios",
      "NestJS",
      "Docker",
      "GitLab",
      "Jenkins",
      "Bree",
      "Redis",
      "Knex",
    ],
  },

  {
    title: "Technical Lead @ Telebort",
    currentJob: false,
    startDate: "Nov 2023",
    endDate: "Mar 2024",
    description: [
      "Guides and directs technical teams in project development, setting coding standards and architectural guidelines",
      "Mentors and supports team members, fostering skill growth and problem-solving abilities",
    ],
    techStack: [
      "NextJS",
      "React",
      "TypeScript",
      "NextUI",
      "TanStack Query",
      "NextAuth",
      "tRPC",
      "Prisma",
      "Stripe",
      "Firebase",
      "Jira",
    ],
  },
];
